name: Meu Primeiro Workflow de CI

on:
  push: 
    branches:
      - main
  workflow_dispatch:

jobs:
  meu-primeiro-job:
    runs-on: ubuntu-latest
    steps:
      - name: Imprime mensagem de boas-vindas
        run: echo "Iniciando meu primeiro job!"
      - name: Mostra o diretório de trabalho
        run: pwd
      - name: Lista arquivos no runner
        run: ls -la
      - name: Lista arquivos no runner
        run: ls -la -a
      - name: Imprime variavel
        run: echo "A variável de ambiente ${{ github.event_name }}"
        name: RA 6324573-Lucas Henrique
        run: RA "6324573-Lucas Henrique"