name: Meu Primeiro Workflow de CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

jobs:
  meu-primeiro-job:
    runs-on: ubuntu-latest
    steps:
      - name: Exibe RA e Nome
        run: echo "RA 6324573 - Lucas Henrique"

      - name: Mostra o diretório de trabalho
        run: pwd

      - name: Imprime nome do repositório
        run: echo "Nome do repositório ${{ github.repository }}"

      - name: Lista arquivos no diretório
        run: ls -la
        name Lista conteúdo do diretório RA:
        run: ls -la RA_6324573_Lucas_Henrique/
